//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xena.Micro.ZipCodeService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Countries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Countries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xena.Micro.ZipCodeService.Countries", typeof(Countries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caribbean.
        /// </summary>
        public static string Localized_Country_029 {
            get {
                return ResourceManager.GetString("Localized_Country_029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andorra.
        /// </summary>
        public static string Localized_Country_AD {
            get {
                return ResourceManager.GetString("Localized_Country_AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Arab Emirates.
        /// </summary>
        public static string Localized_Country_AE {
            get {
                return ResourceManager.GetString("Localized_Country_AE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan.
        /// </summary>
        public static string Localized_Country_AF {
            get {
                return ResourceManager.GetString("Localized_Country_AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antigua and Barbuda.
        /// </summary>
        public static string Localized_Country_AG {
            get {
                return ResourceManager.GetString("Localized_Country_AG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anguilla.
        /// </summary>
        public static string Localized_Country_AI {
            get {
                return ResourceManager.GetString("Localized_Country_AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albania.
        /// </summary>
        public static string Localized_Country_AL {
            get {
                return ResourceManager.GetString("Localized_Country_AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armenia.
        /// </summary>
        public static string Localized_Country_AM {
            get {
                return ResourceManager.GetString("Localized_Country_AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angola.
        /// </summary>
        public static string Localized_Country_AO {
            get {
                return ResourceManager.GetString("Localized_Country_AO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antarctica.
        /// </summary>
        public static string Localized_Country_AQ {
            get {
                return ResourceManager.GetString("Localized_Country_AQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentina.
        /// </summary>
        public static string Localized_Country_AR {
            get {
                return ResourceManager.GetString("Localized_Country_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American Samoa.
        /// </summary>
        public static string Localized_Country_AS {
            get {
                return ResourceManager.GetString("Localized_Country_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Austria.
        /// </summary>
        public static string Localized_Country_AT {
            get {
                return ResourceManager.GetString("Localized_Country_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia.
        /// </summary>
        public static string Localized_Country_AU {
            get {
                return ResourceManager.GetString("Localized_Country_AU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aruba.
        /// </summary>
        public static string Localized_Country_AW {
            get {
                return ResourceManager.GetString("Localized_Country_AW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Åland Islands.
        /// </summary>
        public static string Localized_Country_AX {
            get {
                return ResourceManager.GetString("Localized_Country_AX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan.
        /// </summary>
        public static string Localized_Country_AZ {
            get {
                return ResourceManager.GetString("Localized_Country_AZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosnia and Herzegovina.
        /// </summary>
        public static string Localized_Country_BA {
            get {
                return ResourceManager.GetString("Localized_Country_BA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbados.
        /// </summary>
        public static string Localized_Country_BB {
            get {
                return ResourceManager.GetString("Localized_Country_BB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangladesh.
        /// </summary>
        public static string Localized_Country_BD {
            get {
                return ResourceManager.GetString("Localized_Country_BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgium.
        /// </summary>
        public static string Localized_Country_BE {
            get {
                return ResourceManager.GetString("Localized_Country_BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burkina Faso.
        /// </summary>
        public static string Localized_Country_BF {
            get {
                return ResourceManager.GetString("Localized_Country_BF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgaria.
        /// </summary>
        public static string Localized_Country_BG {
            get {
                return ResourceManager.GetString("Localized_Country_BG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahrain.
        /// </summary>
        public static string Localized_Country_BH {
            get {
                return ResourceManager.GetString("Localized_Country_BH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burundi.
        /// </summary>
        public static string Localized_Country_BI {
            get {
                return ResourceManager.GetString("Localized_Country_BI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benin.
        /// </summary>
        public static string Localized_Country_BJ {
            get {
                return ResourceManager.GetString("Localized_Country_BJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Barthélemy.
        /// </summary>
        public static string Localized_Country_BL {
            get {
                return ResourceManager.GetString("Localized_Country_BL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bermuda.
        /// </summary>
        public static string Localized_Country_BM {
            get {
                return ResourceManager.GetString("Localized_Country_BM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brunei Darussalam.
        /// </summary>
        public static string Localized_Country_BN {
            get {
                return ResourceManager.GetString("Localized_Country_BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolivia (Plurinational State of).
        /// </summary>
        public static string Localized_Country_BO {
            get {
                return ResourceManager.GetString("Localized_Country_BO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonaire, Sint Eustatius and Saba.
        /// </summary>
        public static string Localized_Country_BQ {
            get {
                return ResourceManager.GetString("Localized_Country_BQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazil.
        /// </summary>
        public static string Localized_Country_BR {
            get {
                return ResourceManager.GetString("Localized_Country_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahamas.
        /// </summary>
        public static string Localized_Country_BS {
            get {
                return ResourceManager.GetString("Localized_Country_BS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bhutan.
        /// </summary>
        public static string Localized_Country_BT {
            get {
                return ResourceManager.GetString("Localized_Country_BT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouvet Island.
        /// </summary>
        public static string Localized_Country_BV {
            get {
                return ResourceManager.GetString("Localized_Country_BV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botswana.
        /// </summary>
        public static string Localized_Country_BW {
            get {
                return ResourceManager.GetString("Localized_Country_BW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belarus.
        /// </summary>
        public static string Localized_Country_BY {
            get {
                return ResourceManager.GetString("Localized_Country_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belize.
        /// </summary>
        public static string Localized_Country_BZ {
            get {
                return ResourceManager.GetString("Localized_Country_BZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada.
        /// </summary>
        public static string Localized_Country_CA {
            get {
                return ResourceManager.GetString("Localized_Country_CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cocos (Keeling) Islands.
        /// </summary>
        public static string Localized_Country_CC {
            get {
                return ResourceManager.GetString("Localized_Country_CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congo (the Democratic Republic of the).
        /// </summary>
        public static string Localized_Country_CD {
            get {
                return ResourceManager.GetString("Localized_Country_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central African Republic.
        /// </summary>
        public static string Localized_Country_CF {
            get {
                return ResourceManager.GetString("Localized_Country_CF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congo.
        /// </summary>
        public static string Localized_Country_CG {
            get {
                return ResourceManager.GetString("Localized_Country_CG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switzerland.
        /// </summary>
        public static string Localized_Country_CH {
            get {
                return ResourceManager.GetString("Localized_Country_CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Côte d&apos;Ivoire.
        /// </summary>
        public static string Localized_Country_CI {
            get {
                return ResourceManager.GetString("Localized_Country_CI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cook Islands.
        /// </summary>
        public static string Localized_Country_CK {
            get {
                return ResourceManager.GetString("Localized_Country_CK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chile.
        /// </summary>
        public static string Localized_Country_CL {
            get {
                return ResourceManager.GetString("Localized_Country_CL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameroon.
        /// </summary>
        public static string Localized_Country_CM {
            get {
                return ResourceManager.GetString("Localized_Country_CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China.
        /// </summary>
        public static string Localized_Country_CN {
            get {
                return ResourceManager.GetString("Localized_Country_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombia.
        /// </summary>
        public static string Localized_Country_CO {
            get {
                return ResourceManager.GetString("Localized_Country_CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costa Rica.
        /// </summary>
        public static string Localized_Country_CR {
            get {
                return ResourceManager.GetString("Localized_Country_CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuba.
        /// </summary>
        public static string Localized_Country_CU {
            get {
                return ResourceManager.GetString("Localized_Country_CU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabo Verde.
        /// </summary>
        public static string Localized_Country_CV {
            get {
                return ResourceManager.GetString("Localized_Country_CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curaçao.
        /// </summary>
        public static string Localized_Country_CW {
            get {
                return ResourceManager.GetString("Localized_Country_CW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christmas Island.
        /// </summary>
        public static string Localized_Country_CX {
            get {
                return ResourceManager.GetString("Localized_Country_CX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyprus.
        /// </summary>
        public static string Localized_Country_CY {
            get {
                return ResourceManager.GetString("Localized_Country_CY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech Republic.
        /// </summary>
        public static string Localized_Country_CZ {
            get {
                return ResourceManager.GetString("Localized_Country_CZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany.
        /// </summary>
        public static string Localized_Country_DE {
            get {
                return ResourceManager.GetString("Localized_Country_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Djibouti.
        /// </summary>
        public static string Localized_Country_DJ {
            get {
                return ResourceManager.GetString("Localized_Country_DJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denmark.
        /// </summary>
        public static string Localized_Country_DK {
            get {
                return ResourceManager.GetString("Localized_Country_DK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominica.
        /// </summary>
        public static string Localized_Country_DM {
            get {
                return ResourceManager.GetString("Localized_Country_DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominican Republic.
        /// </summary>
        public static string Localized_Country_DO {
            get {
                return ResourceManager.GetString("Localized_Country_DO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algeria.
        /// </summary>
        public static string Localized_Country_DZ {
            get {
                return ResourceManager.GetString("Localized_Country_DZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecuador.
        /// </summary>
        public static string Localized_Country_EC {
            get {
                return ResourceManager.GetString("Localized_Country_EC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonia.
        /// </summary>
        public static string Localized_Country_EE {
            get {
                return ResourceManager.GetString("Localized_Country_EE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egypt.
        /// </summary>
        public static string Localized_Country_EG {
            get {
                return ResourceManager.GetString("Localized_Country_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western Sahara.
        /// </summary>
        public static string Localized_Country_EH {
            get {
                return ResourceManager.GetString("Localized_Country_EH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eritrea.
        /// </summary>
        public static string Localized_Country_ER {
            get {
                return ResourceManager.GetString("Localized_Country_ER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain.
        /// </summary>
        public static string Localized_Country_ES {
            get {
                return ResourceManager.GetString("Localized_Country_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethiopia.
        /// </summary>
        public static string Localized_Country_ET {
            get {
                return ResourceManager.GetString("Localized_Country_ET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finland.
        /// </summary>
        public static string Localized_Country_FI {
            get {
                return ResourceManager.GetString("Localized_Country_FI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiji.
        /// </summary>
        public static string Localized_Country_FJ {
            get {
                return ResourceManager.GetString("Localized_Country_FJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falkland Islands [Malvinas].
        /// </summary>
        public static string Localized_Country_FK {
            get {
                return ResourceManager.GetString("Localized_Country_FK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micronesia (Federated States of).
        /// </summary>
        public static string Localized_Country_FM {
            get {
                return ResourceManager.GetString("Localized_Country_FM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faroe Islands.
        /// </summary>
        public static string Localized_Country_FO {
            get {
                return ResourceManager.GetString("Localized_Country_FO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France.
        /// </summary>
        public static string Localized_Country_FR {
            get {
                return ResourceManager.GetString("Localized_Country_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gabon.
        /// </summary>
        public static string Localized_Country_GA {
            get {
                return ResourceManager.GetString("Localized_Country_GA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Kingdom of Great Britain and Northern Ireland.
        /// </summary>
        public static string Localized_Country_GB {
            get {
                return ResourceManager.GetString("Localized_Country_GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grenada.
        /// </summary>
        public static string Localized_Country_GD {
            get {
                return ResourceManager.GetString("Localized_Country_GD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgia.
        /// </summary>
        public static string Localized_Country_GE {
            get {
                return ResourceManager.GetString("Localized_Country_GE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Guiana.
        /// </summary>
        public static string Localized_Country_GF {
            get {
                return ResourceManager.GetString("Localized_Country_GF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guernsey.
        /// </summary>
        public static string Localized_Country_GG {
            get {
                return ResourceManager.GetString("Localized_Country_GG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghana.
        /// </summary>
        public static string Localized_Country_GH {
            get {
                return ResourceManager.GetString("Localized_Country_GH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibraltar.
        /// </summary>
        public static string Localized_Country_GI {
            get {
                return ResourceManager.GetString("Localized_Country_GI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenland.
        /// </summary>
        public static string Localized_Country_GL {
            get {
                return ResourceManager.GetString("Localized_Country_GL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gambia.
        /// </summary>
        public static string Localized_Country_GM {
            get {
                return ResourceManager.GetString("Localized_Country_GM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guinea.
        /// </summary>
        public static string Localized_Country_GN {
            get {
                return ResourceManager.GetString("Localized_Country_GN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guadeloupe.
        /// </summary>
        public static string Localized_Country_GP {
            get {
                return ResourceManager.GetString("Localized_Country_GP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equatorial Guinea.
        /// </summary>
        public static string Localized_Country_GQ {
            get {
                return ResourceManager.GetString("Localized_Country_GQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greece.
        /// </summary>
        public static string Localized_Country_GR {
            get {
                return ResourceManager.GetString("Localized_Country_GR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Georgia and the South Sandwich Islands.
        /// </summary>
        public static string Localized_Country_GS {
            get {
                return ResourceManager.GetString("Localized_Country_GS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guatemala.
        /// </summary>
        public static string Localized_Country_GT {
            get {
                return ResourceManager.GetString("Localized_Country_GT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guam.
        /// </summary>
        public static string Localized_Country_GU {
            get {
                return ResourceManager.GetString("Localized_Country_GU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guinea-Bissau.
        /// </summary>
        public static string Localized_Country_GW {
            get {
                return ResourceManager.GetString("Localized_Country_GW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guyana.
        /// </summary>
        public static string Localized_Country_GY {
            get {
                return ResourceManager.GetString("Localized_Country_GY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hong Kong.
        /// </summary>
        public static string Localized_Country_HK {
            get {
                return ResourceManager.GetString("Localized_Country_HK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heard Island and McDonald Islands.
        /// </summary>
        public static string Localized_Country_HM {
            get {
                return ResourceManager.GetString("Localized_Country_HM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honduras.
        /// </summary>
        public static string Localized_Country_HN {
            get {
                return ResourceManager.GetString("Localized_Country_HN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatia.
        /// </summary>
        public static string Localized_Country_HR {
            get {
                return ResourceManager.GetString("Localized_Country_HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haiti.
        /// </summary>
        public static string Localized_Country_HT {
            get {
                return ResourceManager.GetString("Localized_Country_HT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungary.
        /// </summary>
        public static string Localized_Country_HU {
            get {
                return ResourceManager.GetString("Localized_Country_HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesia.
        /// </summary>
        public static string Localized_Country_ID {
            get {
                return ResourceManager.GetString("Localized_Country_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ireland.
        /// </summary>
        public static string Localized_Country_IE {
            get {
                return ResourceManager.GetString("Localized_Country_IE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Israel.
        /// </summary>
        public static string Localized_Country_IL {
            get {
                return ResourceManager.GetString("Localized_Country_IL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isle of Man.
        /// </summary>
        public static string Localized_Country_IM {
            get {
                return ResourceManager.GetString("Localized_Country_IM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to India.
        /// </summary>
        public static string Localized_Country_IN {
            get {
                return ResourceManager.GetString("Localized_Country_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British Indian Ocean Territory.
        /// </summary>
        public static string Localized_Country_IO {
            get {
                return ResourceManager.GetString("Localized_Country_IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iraq.
        /// </summary>
        public static string Localized_Country_IQ {
            get {
                return ResourceManager.GetString("Localized_Country_IQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran (Islamic Republic of).
        /// </summary>
        public static string Localized_Country_IR {
            get {
                return ResourceManager.GetString("Localized_Country_IR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iceland.
        /// </summary>
        public static string Localized_Country_IS {
            get {
                return ResourceManager.GetString("Localized_Country_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italy.
        /// </summary>
        public static string Localized_Country_IT {
            get {
                return ResourceManager.GetString("Localized_Country_IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jersey.
        /// </summary>
        public static string Localized_Country_JE {
            get {
                return ResourceManager.GetString("Localized_Country_JE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jamaica.
        /// </summary>
        public static string Localized_Country_JM {
            get {
                return ResourceManager.GetString("Localized_Country_JM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jordan.
        /// </summary>
        public static string Localized_Country_JO {
            get {
                return ResourceManager.GetString("Localized_Country_JO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan.
        /// </summary>
        public static string Localized_Country_JP {
            get {
                return ResourceManager.GetString("Localized_Country_JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kenya.
        /// </summary>
        public static string Localized_Country_KE {
            get {
                return ResourceManager.GetString("Localized_Country_KE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyrgyzstan.
        /// </summary>
        public static string Localized_Country_KG {
            get {
                return ResourceManager.GetString("Localized_Country_KG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambodia.
        /// </summary>
        public static string Localized_Country_KH {
            get {
                return ResourceManager.GetString("Localized_Country_KH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiribati.
        /// </summary>
        public static string Localized_Country_KI {
            get {
                return ResourceManager.GetString("Localized_Country_KI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comoros.
        /// </summary>
        public static string Localized_Country_KM {
            get {
                return ResourceManager.GetString("Localized_Country_KM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Kitts and Nevis.
        /// </summary>
        public static string Localized_Country_KN {
            get {
                return ResourceManager.GetString("Localized_Country_KN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korea (the Democratic People&apos;s Republic of).
        /// </summary>
        public static string Localized_Country_KP {
            get {
                return ResourceManager.GetString("Localized_Country_KP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korea (the Republic of).
        /// </summary>
        public static string Localized_Country_KR {
            get {
                return ResourceManager.GetString("Localized_Country_KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuwait.
        /// </summary>
        public static string Localized_Country_KW {
            get {
                return ResourceManager.GetString("Localized_Country_KW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cayman Islands.
        /// </summary>
        public static string Localized_Country_KY {
            get {
                return ResourceManager.GetString("Localized_Country_KY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazakhstan.
        /// </summary>
        public static string Localized_Country_KZ {
            get {
                return ResourceManager.GetString("Localized_Country_KZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lao People&apos;s Democratic Republic.
        /// </summary>
        public static string Localized_Country_LA {
            get {
                return ResourceManager.GetString("Localized_Country_LA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lebanon.
        /// </summary>
        public static string Localized_Country_LB {
            get {
                return ResourceManager.GetString("Localized_Country_LB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Lucia.
        /// </summary>
        public static string Localized_Country_LC {
            get {
                return ResourceManager.GetString("Localized_Country_LC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liechtenstein.
        /// </summary>
        public static string Localized_Country_LI {
            get {
                return ResourceManager.GetString("Localized_Country_LI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sri Lanka.
        /// </summary>
        public static string Localized_Country_LK {
            get {
                return ResourceManager.GetString("Localized_Country_LK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberia.
        /// </summary>
        public static string Localized_Country_LR {
            get {
                return ResourceManager.GetString("Localized_Country_LR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesotho.
        /// </summary>
        public static string Localized_Country_LS {
            get {
                return ResourceManager.GetString("Localized_Country_LS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithuania.
        /// </summary>
        public static string Localized_Country_LT {
            get {
                return ResourceManager.GetString("Localized_Country_LT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxembourg.
        /// </summary>
        public static string Localized_Country_LU {
            get {
                return ResourceManager.GetString("Localized_Country_LU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvia.
        /// </summary>
        public static string Localized_Country_LV {
            get {
                return ResourceManager.GetString("Localized_Country_LV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libya.
        /// </summary>
        public static string Localized_Country_LY {
            get {
                return ResourceManager.GetString("Localized_Country_LY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morocco.
        /// </summary>
        public static string Localized_Country_MA {
            get {
                return ResourceManager.GetString("Localized_Country_MA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monaco.
        /// </summary>
        public static string Localized_Country_MC {
            get {
                return ResourceManager.GetString("Localized_Country_MC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moldova (the Republic of).
        /// </summary>
        public static string Localized_Country_MD {
            get {
                return ResourceManager.GetString("Localized_Country_MD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montenegro.
        /// </summary>
        public static string Localized_Country_ME {
            get {
                return ResourceManager.GetString("Localized_Country_ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Martin (French part).
        /// </summary>
        public static string Localized_Country_MF {
            get {
                return ResourceManager.GetString("Localized_Country_MF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madagascar.
        /// </summary>
        public static string Localized_Country_MG {
            get {
                return ResourceManager.GetString("Localized_Country_MG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marshall Islands.
        /// </summary>
        public static string Localized_Country_MH {
            get {
                return ResourceManager.GetString("Localized_Country_MH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macedonia (the former Yugoslav Republic of).
        /// </summary>
        public static string Localized_Country_MK {
            get {
                return ResourceManager.GetString("Localized_Country_MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mali.
        /// </summary>
        public static string Localized_Country_ML {
            get {
                return ResourceManager.GetString("Localized_Country_ML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myanmar.
        /// </summary>
        public static string Localized_Country_MM {
            get {
                return ResourceManager.GetString("Localized_Country_MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mongolia.
        /// </summary>
        public static string Localized_Country_MN {
            get {
                return ResourceManager.GetString("Localized_Country_MN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macao.
        /// </summary>
        public static string Localized_Country_MO {
            get {
                return ResourceManager.GetString("Localized_Country_MO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northern Mariana Islands.
        /// </summary>
        public static string Localized_Country_MP {
            get {
                return ResourceManager.GetString("Localized_Country_MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martinique.
        /// </summary>
        public static string Localized_Country_MQ {
            get {
                return ResourceManager.GetString("Localized_Country_MQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauritania.
        /// </summary>
        public static string Localized_Country_MR {
            get {
                return ResourceManager.GetString("Localized_Country_MR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montserrat.
        /// </summary>
        public static string Localized_Country_MS {
            get {
                return ResourceManager.GetString("Localized_Country_MS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malta.
        /// </summary>
        public static string Localized_Country_MT {
            get {
                return ResourceManager.GetString("Localized_Country_MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauritius.
        /// </summary>
        public static string Localized_Country_MU {
            get {
                return ResourceManager.GetString("Localized_Country_MU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maldives.
        /// </summary>
        public static string Localized_Country_MV {
            get {
                return ResourceManager.GetString("Localized_Country_MV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malawi.
        /// </summary>
        public static string Localized_Country_MW {
            get {
                return ResourceManager.GetString("Localized_Country_MW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexico.
        /// </summary>
        public static string Localized_Country_MX {
            get {
                return ResourceManager.GetString("Localized_Country_MX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaysia.
        /// </summary>
        public static string Localized_Country_MY {
            get {
                return ResourceManager.GetString("Localized_Country_MY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozambique.
        /// </summary>
        public static string Localized_Country_MZ {
            get {
                return ResourceManager.GetString("Localized_Country_MZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namibia.
        /// </summary>
        public static string Localized_Country_NA {
            get {
                return ResourceManager.GetString("Localized_Country_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Caledonia.
        /// </summary>
        public static string Localized_Country_NC {
            get {
                return ResourceManager.GetString("Localized_Country_NC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niger.
        /// </summary>
        public static string Localized_Country_NE {
            get {
                return ResourceManager.GetString("Localized_Country_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norfolk Island.
        /// </summary>
        public static string Localized_Country_NF {
            get {
                return ResourceManager.GetString("Localized_Country_NF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nigeria.
        /// </summary>
        public static string Localized_Country_NG {
            get {
                return ResourceManager.GetString("Localized_Country_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicaragua.
        /// </summary>
        public static string Localized_Country_NI {
            get {
                return ResourceManager.GetString("Localized_Country_NI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netherlands.
        /// </summary>
        public static string Localized_Country_NL {
            get {
                return ResourceManager.GetString("Localized_Country_NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norway.
        /// </summary>
        public static string Localized_Country_NO {
            get {
                return ResourceManager.GetString("Localized_Country_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepal.
        /// </summary>
        public static string Localized_Country_NP {
            get {
                return ResourceManager.GetString("Localized_Country_NP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nauru.
        /// </summary>
        public static string Localized_Country_NR {
            get {
                return ResourceManager.GetString("Localized_Country_NR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niue.
        /// </summary>
        public static string Localized_Country_NU {
            get {
                return ResourceManager.GetString("Localized_Country_NU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Zealand.
        /// </summary>
        public static string Localized_Country_NZ {
            get {
                return ResourceManager.GetString("Localized_Country_NZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oman.
        /// </summary>
        public static string Localized_Country_OM {
            get {
                return ResourceManager.GetString("Localized_Country_OM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panama.
        /// </summary>
        public static string Localized_Country_PA {
            get {
                return ResourceManager.GetString("Localized_Country_PA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peru.
        /// </summary>
        public static string Localized_Country_PE {
            get {
                return ResourceManager.GetString("Localized_Country_PE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Polynesia.
        /// </summary>
        public static string Localized_Country_PF {
            get {
                return ResourceManager.GetString("Localized_Country_PF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papua New Guinea.
        /// </summary>
        public static string Localized_Country_PG {
            get {
                return ResourceManager.GetString("Localized_Country_PG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philippines.
        /// </summary>
        public static string Localized_Country_PH {
            get {
                return ResourceManager.GetString("Localized_Country_PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pakistan.
        /// </summary>
        public static string Localized_Country_PK {
            get {
                return ResourceManager.GetString("Localized_Country_PK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poland.
        /// </summary>
        public static string Localized_Country_PL {
            get {
                return ResourceManager.GetString("Localized_Country_PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Pierre and Miquelon.
        /// </summary>
        public static string Localized_Country_PM {
            get {
                return ResourceManager.GetString("Localized_Country_PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitcairn.
        /// </summary>
        public static string Localized_Country_PN {
            get {
                return ResourceManager.GetString("Localized_Country_PN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto Rico.
        /// </summary>
        public static string Localized_Country_PR {
            get {
                return ResourceManager.GetString("Localized_Country_PR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palestine, State of.
        /// </summary>
        public static string Localized_Country_PS {
            get {
                return ResourceManager.GetString("Localized_Country_PS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugal.
        /// </summary>
        public static string Localized_Country_PT {
            get {
                return ResourceManager.GetString("Localized_Country_PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palau.
        /// </summary>
        public static string Localized_Country_PW {
            get {
                return ResourceManager.GetString("Localized_Country_PW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paraguay.
        /// </summary>
        public static string Localized_Country_PY {
            get {
                return ResourceManager.GetString("Localized_Country_PY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qatar.
        /// </summary>
        public static string Localized_Country_QA {
            get {
                return ResourceManager.GetString("Localized_Country_QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réunion.
        /// </summary>
        public static string Localized_Country_RE {
            get {
                return ResourceManager.GetString("Localized_Country_RE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romania.
        /// </summary>
        public static string Localized_Country_RO {
            get {
                return ResourceManager.GetString("Localized_Country_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbia.
        /// </summary>
        public static string Localized_Country_RS {
            get {
                return ResourceManager.GetString("Localized_Country_RS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian Federation.
        /// </summary>
        public static string Localized_Country_RU {
            get {
                return ResourceManager.GetString("Localized_Country_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rwanda.
        /// </summary>
        public static string Localized_Country_RW {
            get {
                return ResourceManager.GetString("Localized_Country_RW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudi Arabia.
        /// </summary>
        public static string Localized_Country_SA {
            get {
                return ResourceManager.GetString("Localized_Country_SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solomon Islands.
        /// </summary>
        public static string Localized_Country_SB {
            get {
                return ResourceManager.GetString("Localized_Country_SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seychelles.
        /// </summary>
        public static string Localized_Country_SC {
            get {
                return ResourceManager.GetString("Localized_Country_SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudan.
        /// </summary>
        public static string Localized_Country_SD {
            get {
                return ResourceManager.GetString("Localized_Country_SD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweden.
        /// </summary>
        public static string Localized_Country_SE {
            get {
                return ResourceManager.GetString("Localized_Country_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singapore.
        /// </summary>
        public static string Localized_Country_SG {
            get {
                return ResourceManager.GetString("Localized_Country_SG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Helena, Ascension and Tristan da Cunha.
        /// </summary>
        public static string Localized_Country_SH {
            get {
                return ResourceManager.GetString("Localized_Country_SH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenia.
        /// </summary>
        public static string Localized_Country_SI {
            get {
                return ResourceManager.GetString("Localized_Country_SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svalbard and Jan Mayen.
        /// </summary>
        public static string Localized_Country_SJ {
            get {
                return ResourceManager.GetString("Localized_Country_SJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovakia.
        /// </summary>
        public static string Localized_Country_SK {
            get {
                return ResourceManager.GetString("Localized_Country_SK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sierra Leone.
        /// </summary>
        public static string Localized_Country_SL {
            get {
                return ResourceManager.GetString("Localized_Country_SL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to San Marino.
        /// </summary>
        public static string Localized_Country_SM {
            get {
                return ResourceManager.GetString("Localized_Country_SM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senegal.
        /// </summary>
        public static string Localized_Country_SN {
            get {
                return ResourceManager.GetString("Localized_Country_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somalia.
        /// </summary>
        public static string Localized_Country_SO {
            get {
                return ResourceManager.GetString("Localized_Country_SO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suriname.
        /// </summary>
        public static string Localized_Country_SR {
            get {
                return ResourceManager.GetString("Localized_Country_SR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Sudan.
        /// </summary>
        public static string Localized_Country_SS {
            get {
                return ResourceManager.GetString("Localized_Country_SS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao Tome and Principe.
        /// </summary>
        public static string Localized_Country_ST {
            get {
                return ResourceManager.GetString("Localized_Country_ST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Salvador.
        /// </summary>
        public static string Localized_Country_SV {
            get {
                return ResourceManager.GetString("Localized_Country_SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sint Maarten (Dutch part).
        /// </summary>
        public static string Localized_Country_SX {
            get {
                return ResourceManager.GetString("Localized_Country_SX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syrian Arab Republic.
        /// </summary>
        public static string Localized_Country_SY {
            get {
                return ResourceManager.GetString("Localized_Country_SY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swaziland.
        /// </summary>
        public static string Localized_Country_SZ {
            get {
                return ResourceManager.GetString("Localized_Country_SZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turks and Caicos Islands.
        /// </summary>
        public static string Localized_Country_TC {
            get {
                return ResourceManager.GetString("Localized_Country_TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chad.
        /// </summary>
        public static string Localized_Country_TD {
            get {
                return ResourceManager.GetString("Localized_Country_TD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Southern Territories.
        /// </summary>
        public static string Localized_Country_TF {
            get {
                return ResourceManager.GetString("Localized_Country_TF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Togo.
        /// </summary>
        public static string Localized_Country_TG {
            get {
                return ResourceManager.GetString("Localized_Country_TG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thailand.
        /// </summary>
        public static string Localized_Country_TH {
            get {
                return ResourceManager.GetString("Localized_Country_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tajikistan.
        /// </summary>
        public static string Localized_Country_TJ {
            get {
                return ResourceManager.GetString("Localized_Country_TJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokelau.
        /// </summary>
        public static string Localized_Country_TK {
            get {
                return ResourceManager.GetString("Localized_Country_TK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timor-Leste.
        /// </summary>
        public static string Localized_Country_TL {
            get {
                return ResourceManager.GetString("Localized_Country_TL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkmenistan.
        /// </summary>
        public static string Localized_Country_TM {
            get {
                return ResourceManager.GetString("Localized_Country_TM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunisia.
        /// </summary>
        public static string Localized_Country_TN {
            get {
                return ResourceManager.GetString("Localized_Country_TN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonga.
        /// </summary>
        public static string Localized_Country_TO {
            get {
                return ResourceManager.GetString("Localized_Country_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey.
        /// </summary>
        public static string Localized_Country_TR {
            get {
                return ResourceManager.GetString("Localized_Country_TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trinidad and Tobago.
        /// </summary>
        public static string Localized_Country_TT {
            get {
                return ResourceManager.GetString("Localized_Country_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuvalu.
        /// </summary>
        public static string Localized_Country_TV {
            get {
                return ResourceManager.GetString("Localized_Country_TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taiwan (Province of China).
        /// </summary>
        public static string Localized_Country_TW {
            get {
                return ResourceManager.GetString("Localized_Country_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanzania, United Republic of.
        /// </summary>
        public static string Localized_Country_TZ {
            get {
                return ResourceManager.GetString("Localized_Country_TZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukraine.
        /// </summary>
        public static string Localized_Country_UA {
            get {
                return ResourceManager.GetString("Localized_Country_UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uganda.
        /// </summary>
        public static string Localized_Country_UG {
            get {
                return ResourceManager.GetString("Localized_Country_UG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States Minor Outlying Islands.
        /// </summary>
        public static string Localized_Country_UM {
            get {
                return ResourceManager.GetString("Localized_Country_UM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States of America.
        /// </summary>
        public static string Localized_Country_US {
            get {
                return ResourceManager.GetString("Localized_Country_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruguay.
        /// </summary>
        public static string Localized_Country_UY {
            get {
                return ResourceManager.GetString("Localized_Country_UY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzbekistan.
        /// </summary>
        public static string Localized_Country_UZ {
            get {
                return ResourceManager.GetString("Localized_Country_UZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holy See.
        /// </summary>
        public static string Localized_Country_VA {
            get {
                return ResourceManager.GetString("Localized_Country_VA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Vincent and the Grenadines.
        /// </summary>
        public static string Localized_Country_VC {
            get {
                return ResourceManager.GetString("Localized_Country_VC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venezuela (Bolivarian Republic of).
        /// </summary>
        public static string Localized_Country_VE {
            get {
                return ResourceManager.GetString("Localized_Country_VE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virgin Islands (British).
        /// </summary>
        public static string Localized_Country_VG {
            get {
                return ResourceManager.GetString("Localized_Country_VG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virgin Islands (U.S.).
        /// </summary>
        public static string Localized_Country_VI {
            get {
                return ResourceManager.GetString("Localized_Country_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viet Nam.
        /// </summary>
        public static string Localized_Country_VN {
            get {
                return ResourceManager.GetString("Localized_Country_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanuatu.
        /// </summary>
        public static string Localized_Country_VU {
            get {
                return ResourceManager.GetString("Localized_Country_VU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallis and Futuna.
        /// </summary>
        public static string Localized_Country_WF {
            get {
                return ResourceManager.GetString("Localized_Country_WF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samoa.
        /// </summary>
        public static string Localized_Country_WS {
            get {
                return ResourceManager.GetString("Localized_Country_WS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemen.
        /// </summary>
        public static string Localized_Country_YE {
            get {
                return ResourceManager.GetString("Localized_Country_YE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayotte.
        /// </summary>
        public static string Localized_Country_YT {
            get {
                return ResourceManager.GetString("Localized_Country_YT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Africa.
        /// </summary>
        public static string Localized_Country_ZA {
            get {
                return ResourceManager.GetString("Localized_Country_ZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zambia.
        /// </summary>
        public static string Localized_Country_ZM {
            get {
                return ResourceManager.GetString("Localized_Country_ZM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zimbabwe.
        /// </summary>
        public static string Localized_Country_ZW {
            get {
                return ResourceManager.GetString("Localized_Country_ZW", resourceCulture);
            }
        }
    }
}
